### ISSUE TITLE
Some problems of Coffeeshop-requirements

### ISSUE THREAD

**Issue by FongX777** [humank/EventStormingWorkShop#14]
## 咖啡店內

> 5. 當客人在店內點咖啡時，咖啡溫度需要維持在70度，便於客戶飲用，若客戶是外帶則會需要把製作溫度調高到90度

There are two kinds of temperature need to be considered: **brewing temperature**, **serving temperature**. Which one did you refer?  I think the serving temperature is the answer, but do we need to consider about the brewing temperature?
FYI, [Are You Serving Coffee at the Ideal Temperature?](https://www.littlecoffeeplace.com/coffee-ideal-temperature) 
-> Espresso brewing temperature: 88°C-98°C

> 7. 每一份現煮咖啡我們是義式咖啡的製作方式，每一份濃縮咖啡我們稱之為一個 Shot

What is the size of one shot?
FYI, [Espresso wiki - shot variables](https://en.wikipedia.org/wiki/Espresso#Shot_variables):
The size can be a single, double, or triple, using a proportional amount of ground coffee, roughly 7 (25ml), 14 (50ml), and 21 (75ml) grams

> 9. 盛上述咖啡品項基本單價小杯分別為: 120, 80 , 100, 130, 140 .. 每一杯的飲料大小往上加一級則多加20元

Typos, it should be 80, 100, 120, 140

> 12. 當有任何一個原物料的庫存低於30%，需要通知咖啡師與櫃檯進行補貨，可以通過簡訊、email，而真正去購買原料的是由櫃檯人員去負責
> 13. 買回來的原物料讓咖啡師確認品項狀態與數量後入庫
>14. 希望未來可以有個可視覺化的呈現頁面去看到原料使用狀態、每月熱銷排行、每週熱銷排行
> 15. 每一次補貨都將該物料補到100%，並且需要在3天內到貨完成

I think the 12th, 13th, 14th(not sure), 15th item belong to "進貨原物料"

## 進貨原物料

> 1. 購買牛奶時會需要提供低脂牛奶 (Low-fat Milk)或者 豆奶(Soy Milk)

This one should sit in "提供客製化體驗需求"

## 製作咖啡

> 6. 美式咖啡 - 製作成分為 1 shot 濃縮咖啡與水

How much water do we need?
Take [美式咖啡](https://zh.wikipedia.org/wiki/%E7%BE%8E%E5%BC%8F%E5%92%96%E5%95%A1) as reference, I think 1:12 is a candidate.

**Comment by humank** [comment]
Thanks for the recommendation, all of the these has been merged into document.
