### ISSUE TITLE
Menu Proposal

### ISSUE THREAD

**Issue by FongX777** [humank/EventStormingWorkShop#16]
1 shot: 20g -> 1oz: 30 ml
dry foam (only for cappuccino): more foam less milk
wet foam (only for cappuccino): less foam more milk

| Item / size                | size  | price | recipe                                          |
| -------------------------- | ----- | ----- | ----------------------------------------------- |
| Espresso / Solo            | 30ml  | 60    | 1 shot (30ml)                                   |
| Espresso / Doppio          | 60ml  | 80    | 2 shot (60ml)                                   |
| Caffe Americano / Short    | 240ml | 80    | 1 shot (30ml) + 210ml water                     |
| Caffe Americano / Tall     | 360ml | 100   | 1 shot (30ml) + 330ml water                     |
| Caffe Americano / Granti   | 480ml | 120   | 2 shot (60ml) + 420ml water                     |
| Caffe Americano / Vanti    | 600ml | 140   | 2 shot (60ml) + 540ml water                     |
| Caffe Latte / Short        | 240ml | 100   | 1 shot (30ml) + 210ml milk (with a little foam) |
| Caffe Latte / Tall         | 360ml | 120   | 1 shot (30ml) + 330ml milk (with a little foam) |
| Caffe Latte / Granti       | 480ml | 140   | 2 shot (60ml) + 420ml milk (with a little foam) |
| Caffe Latte / Vanti        | 600ml | 160   | 2 shot (60ml) + 540ml milk (with a little foam) |
| Cappuccino / Short         | 240ml | 100   | 1 shot (30ml) + 105ml milk + 105ml dry/wet foam |
| Cappuccino / Tall          | 360ml | 120   | 1 shot (30ml) + 120ml milk + 120ml dry/wet foam |
| Cappuccino / Granti        | 480ml | 140   | 2 shot (60ml) + 210ml milk + 210ml dry/wet foam |
| Cappuccino / Vanti         | 600ml | 160   | 2 shot (60ml) + 220ml milk + 220ml dry/wet foam |
| Cappuccino / whipped cream | 20 ml | +20   |                                                 |

Other ideas:

1. 通常咖啡店如 Starbucks 不會賣到小杯 (比例比較難調)
2. Dry Foam 是從牛奶發泡而來，沒有規定一定或最小的牛奶量才能製作，所以「需要2杯牛奶」可能不太好調配。
3. Whip Cream 通常是像配料一樣加上去，不用特別再製作

---
References:
- [starbucks](https://www.starbucks.com.tw/products/drinks/view.jspx?cat=beverages)
- [咖啡師必學技能| 製作 ​ 一杯理想的意式濃縮 ESPRESSO](https://caffes.me/2017/07/26/%E5%92%96%E5%95%A1%E5%B8%AB%E5%BF%85%E5%AD%B8%E6%8A%80%E8%83%BD-%E8%A3%BD%E4%BD%9C%E2%80%8B%E4%B8%80%E6%9D%AF%E7%90%86%E6%83%B3%E7%9A%84%E6%84%8F%E5%BC%8F%E6%BF%83%E7%B8%AEespresso/)
- https://www.foodnext.net/science/machining/paper/4111179619
- [【揭密】星巴克點中杯是蠢貨？　咖啡還真的沒比較多](https://ioutaipei.pixnet.net/blog/post/459268261-%E3%80%90%E6%8F%AD%E5%AF%86%E3%80%91%E6%98%9F%E5%B7%B4%E5%85%8B%E9%BB%9E%E4%B8%AD%E6%9D%AF%E6%98%AF%E8%A0%A2%E8%B2%A8%EF%BC%9F-%E5%92%96%E5%95%A1%E9%82%84%E7%9C%9F%E7%9A%84)
- https://www.wowlavie.com/life_unit.php?article_id=AE1700004
- [How many shots of espresso are in a "tall" Starbucks drink?](https://www.quora.com/How-many-shots-of-espresso-are-in-a-tall-Starbucks-drink)
- [Starbucks Drink Guide: Terms](https://delishably.com/dining-out/Starbucks-Drink-Guide-Terms)

![image](https://user-images.githubusercontent.com/14963179/62676794-9f6b5300-b9de-11e9-8eeb-4ae48024f0e8.png)

**Comment by humank** [comment]
great feedback, thanks Fong. With your effort make this sample more real.
